import Head from "next/head";
import styles from "../styles/layout.module.css";

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Public-def Schedule Importer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          <a
            href="https://case.publicdef.net"
            target="_blank"
            rel="noopener noreferrer"
          >
            국선 일정
          </a>
          을 &nbsp;
          <a
            href="https://calendar.google.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            구글 캘린더
          </a>
          로
        </h3>
        <section className={styles.section}>{children}</section>
      </main>

      <footer className={styles.footer}>
        Developed by&nbsp;<span style={{ fontWeight: "bold" }}>JYS</span>
      </footer>
    </div>
  );
}
