import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
// import { google } from "googleapis";

// export async function getServerSideProps() {
//   const res = await fetch("http://localhost:3000/api/getData");
//   const json = res.json();
//   return {
//     props: json,
//   };
// }

const getData = async () => {
  const res = await fetch("/api/getData");
  const json = await res.json();
  return json;
};

export default function Home() {
  const router = useRouter();
  const curStateText = {
    wait: "로그인 정보를 입력하세요.",
    loggedIn: "로그인 성공.",
    loading: "스케줄 로딩 중입니다.",
    loaded: "로딩 완료!",
  };
  const [currentState, setCurrentState] = useState(curStateText.wait);
  const [schedules, setSchedules] = useState([]);

  // const oauth2Client = new google.auth.OAuth2(
  //   "850040068289-gshv3nt5g98npo3s7v7nm8h6h28hhk23.apps.googleusercontent.com",
  //   "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"
  // );

  return (
    <div className={styles.container}>
      <Head>
        <title>Public-def Schedule Importer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          <a
            href="https://case.publicdef.net"
            target="_blank"
            rel="noopener noreferrer"
          >
            국선 일정
          </a>
          을 &nbsp;
          <a
            href="https://calendar.google.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            구글 캘린더로
          </a>
        </h3>

        <section className={styles.section}>
          <form>
            <div>
              <input placeholder="ID" />
            </div>
            <div>
              <input type="password" placeholder="PW" />
            </div>
          </form>
          <button
            style={{ marginTop: "10px" }}
            onClick={async () => {
              setCurrentState(curStateText.loading);
              const data = await getData();
              setCurrentState(curStateText.loaded);
              setSchedules(data.schedules);
            }}
          >
            시작
          </button>
          <Link href="/api/auth">
            <a>구글 인증</a>
          </Link>
          <div>
            <p style={{ textAlign: "center" }}>{currentState}</p>
            <ul>
              {schedules.map((schedule, index) => (
                <li
                  key={index}
                >{`날짜: ${schedule.date}, 시각: ${schedule.time}, 내용: ${schedule.content}`}</li>
              ))}
            </ul>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        Developed by <span style={{ fontWeight: "bold" }}> JYS</span>
      </footer>
    </div>
  );
}
